!include config.nmake

$(TARGET): $(OBJ_FILES)
	$(LD) $(LDFLAGS) $(OBJ_FILES) /OUT:$(TARGET).w32 $(LIBS)

.cpp.obj:
	$(CC) $(CFLAGS) $<

clean:
	$(RM) *.obj *.w32 *.def *.exp *.lib $(TARGET).w32

.PHONY: clean

